using System;
using Backend.KlaseZaRadSaPodacima.DTObjekti.Interfejsi.ZahteviZaDodavanjeIliAzuriranjeMaterijala;
using Backend.KlaseZaRadSaPodacima.FluentValidatori.ValidatoriZaPonovnoKoriscenje.Materijali;
using Backend.KlaseZaRadSaPodacima.PomocneKlase.Enumeracije;
using Backend.KlaseZaRadSaPodacima.PomocneKlase.Interfejsi.PomocniciValidatora;
using Backend.KlaseZaRadSaPodacima.PomocneKlase.Interfejsi.PomocniciValidatora.Parametri;
using Backend.KlaseZaRadSaPodacima.PomocneKlase.Interfejsi.PomocniciValidatora.Parametri.Podesavanja;
using FluentValidation;

namespace Backend.KlaseZaRadSaPodacima.FluentValidatori.ValidatoriZaPonovnoKoriscenje.ZahteviZaDodavanjeIliAzuriranjeMaterijala
{
    public class PutanjaNazivIEkstenzijaMaterijalaZahtevaZaDodavanjeIliAzuriranjeMaterijalaValidator : AbstractValidator<IPutanjaNazivIEkstenzijaMaterijalaZahtevaZaDodavanjeIliAzuriranjeMaterijala>
    {
        public PutanjaNazivIEkstenzijaMaterijalaZahtevaZaDodavanjeIliAzuriranjeMaterijalaValidator(PutanjaNazivIEkstenzijaValidator putanjaNazivIEkstenzijaValidator,
                                                                                                   IPomocnikValidatoraParametara pomocnikValidatoraParametara,
                                                                                                   IPomocnikValidatoraPutanje pomocnikValidatoraPutanje,
                                                                                                   IPodesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala)
        {
            string poruka = null;
            RuleFor(putanjaNazviIEkstenzija => putanjaNazviIEkstenzija).Cascade(CascadeMode.Stop)
                                                                       .Must(putanjaNazivIEkstenzija => pomocnikValidatoraPutanje.DopuniPutanju(putanjaNazivIEkstenzija, false, false, out poruka))
                                                                       .SetValidator(putanjaNazivIEkstenzijaValidator)
                                                                       .DependentRules(() =>
                                                                       {
                                                                           RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Ekstenzija_Materijala,
                                                                                                                                                                                                                                           putanjaNazivIEkstenzija.Ekstenzija,
                                                                                                                                                                                                                                           podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                           "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                           putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                           out poruka))
                                                                                                                                      .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                      .When(putanjaNazivIEkstenzija => string.IsNullOrEmpty(putanjaNazivIEkstenzija.Putanja)
                                                                                                                                                                       && string.IsNullOrEmpty(putanjaNazivIEkstenzija.Naziv)
                                                                                                                                                                       && !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Ekstenzija))
                                                                                                                                      .WithName("Ekstenzija");

                                                                           RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Naziv_Materijala,
                                                                                                                                                                                                                                          putanjaNazivIEkstenzija.Naziv,
                                                                                                                                                                                                                                          podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                          "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                          putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                          out poruka))
                                                                                                                                     .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                     .WithName("Naziv")
                                                                                                                                     .DependentRules(() =>
                                                                                                                                     {
                                                                                                                                         RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Naziv_I_Ekstenzija_Materijala,
                                                                                                                                                                                                                                                                                                                                                                      putanjaNazivIEkstenzija.Naziv + "#" + putanjaNazivIEkstenzija.Ekstenzija,
                                                                                                                                                                                                                                                                                                                                                                      podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                                                                                                                                                      "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                                                                                                                                                      putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                                                                                                                                                      out poruka))
                                                                                                                                                                                                                                                                .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                                                                                                                                                .When(putanjaNazivIEkstenzija => !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Ekstenzija))
                                                                                                                                                                                                                                                                .WithName("Ekstenzija");
                                                                                                                                     })
                                                                                                                                     .When(putanjaNazivIEkstenzija => string.IsNullOrEmpty(putanjaNazivIEkstenzija.Putanja)
                                                                                                                                                                      && !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Naziv));

                                                                           RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Putanja_Nadoblasti_Materijala,
                                                                                                                                                                                                                                         putanjaNazivIEkstenzija.Putanja,
                                                                                                                                                                                                                                         podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                         "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                         putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                         out poruka))
                                                                                                                                    .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                    .WithName("Putanja")
                                                                                                                                    .DependentRules(() =>
                                                                                                                                    {
                                                                                                                                        RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Putanja_Nadoblasti_I_Ekstenzija_Materijala,
                                                                                                                                                                                                                                                                                                        putanjaNazivIEkstenzija.Putanja + "#" + putanjaNazivIEkstenzija.Ekstenzija,
                                                                                                                                                                                                                                                                                                        podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                                                                                        "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                                                                                        putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                                                                                        out poruka))
                                                                                                                                                                                                  .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                                                                                  .When(putanjaNazivIEkstenzija => string.IsNullOrEmpty(putanjaNazivIEkstenzija.Naziv)
                                                                                                                                                                                                                                   && !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Ekstenzija))
                                                                                                                                                                                                  .WithName("Ekstenzija");

                                                                                                                                        RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Putanja_Nadoblasti_I_Naziv_Materijala,
                                                                                                                                                                                                                                                                                                        putanjaNazivIEkstenzija.Putanja + "#" + putanjaNazivIEkstenzija.Naziv,
                                                                                                                                                                                                                                                                                                        podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                                                                                        "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                                                                                        putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                                                                                        out poruka))
                                                                                                                                                                                                  .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                                                                                  .WithName("Naziv")
                                                                                                                                                                                                  .DependentRules(() =>
                                                                                                                                                                                                  {

                                                                                                                                                                                                      RuleFor(putanjaNazivIEkstenzija => putanjaNazivIEkstenzija).Must(putanjaNazivIEkstenzija => pomocnikValidatoraParametara.entitetSaNavedinimParametromVecPostoji(TipProverePostojanjaZahtevaZaDodavanjeIliAzuriranjeMaterijala.Putanja_Nadoblasti_Naziv_I_Ekstenzija_Materijala,
                                                                                                                                                                                                                                                                                                                                                                      putanjaNazivIEkstenzija.Putanja + "#" + putanjaNazivIEkstenzija.Naziv + "#" + putanjaNazivIEkstenzija.Ekstenzija,
                                                                                                                                                                                                                                                                                                                                                                      podesavanjaValidatoraParametaraZahtevaZaDodavanjeIliAzuriranjeMaterijala,
                                                                                                                                                                                                                                                                                                                                                                      "Zahtev za dodavanje ili ažuriranje materijala",
                                                                                                                                                                                                                                                                                                                                                                      putanjaNazivIEkstenzija.OcekivanaVrednostPostojanja,
                                                                                                                                                                                                                                                                                                                                                                      out poruka))
                                                                                                                                                                                                                                                                .WithMessage(putanjaNazivIEkstenzijaValidator => poruka)
                                                                                                                                                                                                                                                                .When(putanjaNazivIEkstenzija => !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Ekstenzija))
                                                                                                                                                                                                                                                                .WithName("Ekstenzija");
                                                                                                                                                                                                  })
                                                                                                                                                                                                  .When(putanjaNazivIEkstenzija => !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Naziv));


                                                                                                                                    })
                                                                                                                                    .When(putanjaNazivIEkstenzija => !string.IsNullOrEmpty(putanjaNazivIEkstenzija.Putanja));


                                                                       });
        }
    }
}